### ISSUE TITLE
QT5SerialTerm

### ISSUE THREAD

**Issue by lrmoreno007** [JorgeAparicio/qSerialTerm#1]
Hi JorgeAparicio, I change some lines of code to adapt it to QT5. please check this link:

https://github.com/lrmoreno007/QT5SerialTerm

If you want what I change something, please tell me.

Thanks for this great code.

**Comment by ricrsantos** [comment]
Hello lrmoreno007, I tried make in Ubuntu 16.04 with QT5 and it not work, could you please share with me your version?
Thanks and best regards!

**Comment by lrmoreno007** [comment]
Hello, my version never got to work properly, that's why I deleted it a long time ago.
